# Site settings
title: Jovinge Lab Bioinformatics
baseurl: ""
url: "http://jovingelabsoftware.github.io"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink: pretty

# Third-party services
# just leave someone empty to disable it
google_analytics: 
disqus_shortname: 

prose:
  rooturl: ""
  metadata:
    "./_posts": |
      layout: post
      title: Enter project title
      abstract: Enter project summary
      author: John Doe
      published: true